### PR TITLE
Re-add metadata

### LINKED ISSUE #129: Restore metadata to the furl object
Before v2.1.0:

```python
>>> import furl
>>> print(furl.__version__)
'2.0.0'
```

With v2.1.0:

```python
>>> import furl
>>> print(furl.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'furl' has no attribute '__version__'
```

The other metadata attributes are missing, too: `__version__`, `__license__`, etc.

### PR DESCRIPTION
**Pull request by ThatXliner**
Possibly fixes #129

### CODE REVIEW

**Comment by gruns** [comment]
Does this work?

This also appears to leave out the other useful metadata variables, like `__license__`, `__description__`, etc. Please add those, too. Thanks!

**Comment by ThatXliner** [comment]
@gruns i actually haven’t tested it yet. I might as well do it today! And if it doesn’t work, I have another idea. This pull request is actually WIP

**Comment by ThatXliner** [comment]
So I added an `__all__` variable in the `__version__.py`. That should fix it.

**Comment by gruns** [comment]
fixed in v2.1.1!

**Pull request closed without merging**
