### PR TITLE
added JSON output for URL

### PR DESCRIPTION
**Pull request by NoobSkywalker**

### CODE REVIEW

**Comment by gruns** [comment]
Huge thank you for your pull request, @NoobSkywalker.

Before I merge, help me understand your motivation for this pull request. For what use(s) do you want to access furl objects (Path objects, Query objects, furl objects, etc) as JSON dictionaries? In what situations is this helpful?

**Comment by NoobSkywalker** [comment]
Hey there. 
Actually for analytics on urls itself as i want to use it to gather metrics on urls and their structure. In the end i want to have a structured representation of a url to train classifiers on the metadata.

**Comment by gruns** [comment]
Thank you for the explanation.

Does a plain Python dictionary suffice for your needs? For example

```python
>>> f = furl('...')
>>> f.asdict()
{ 'scheme': 'http',
  'username': None,
  'password': None,
  'host': 'www.google.com',
  'port': 80,
  'path': <Path object>,
  'path_segments': ['a', 'b', 'c'],  
  'query': <Query object>,
  'query_params': {'a':'a', 'b': 'b'},
  ...
  }
```

A dictionary is simpler -- no JSON involved.

**Comment by NoobSkywalker** [comment]
well i used json as because my program exposes json for other services. Ofc i could do that on my side and it makes sense to provide it as dictionary internally.

**Comment by gruns** [comment]
Wonderful.

I'll modify your code and add `asdict()` to the various URL component objects (Path, Query, Fragment, furl, etc) and update this Issue appropriately.

**Comment by gruns** [comment]
@NoobSkywalker Check out the asdict branch https://github.com/gruns/furl/tree/asdict. Does this suffice for your needs? If so, I'll merge away.

**Comment by NoobSkywalker** [comment]
Great thank you looks good

**Comment by gruns** [comment]
__asdict()__ is now live in furl v1.0.1. Update with

```
pip install furl --upgrade
```

Huge thank you @NoobSkywalker for your issue, pull request, and commits. Don't hesitate to let me know if there's anything else I can do for you.

**Pull request closed without merging**
