### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by medecau**
- removes six dependency definition in tox config
- adds pypy 3 to the list of tests
- changed list of python environments in tox to a pattern permutation

### CODE REVIEW

**Comment by gruns** [comment]
Wonderful pull request, as always Pedro.

A few items:

  1. Help me understand why `six` should be removed from tox.ini's
     `[testenv] deps`. six>=1.8.0 is, of course, required to run furl's
     tests.

     My understanding is that `six` should be removed from `[testenv]` deps
     because six is installed by setup.py, and thus `six` in tox.ini is
     redundant. Is this understanding correct?

  2. Has Tox standardized `pypy3` as PyPy's Python 3+ interpreter? I Googled
     this a few weeks ago but arrived at conflicting resolutions.

      - `pypy3` standardized as generic PyPy Python 3+ interpreter:

         - http://tox.readthedocs.io/en/latest/example/basic.html

      - `pypy3` not yet standardized:

         - https://bitbucket.org/hpk42/tox/issues/345/pypy3-52
         - https://github.com/tox-dev/tox/issues/345

  3. Please revert the changes to `[tox] envlist`, where

     ```
     envlist = codestyle, py26, py27, py33, py34, py35, py36, pypy
     ```

     was changed to

     ```
     envlist = codestyle, py{26,27,33,34,35,36,py,py3}
     ```

     While the former avoid character repitition, it's harder to scan quickly
     because it mangles the words readers are looking for (e.g. `py36` and
     `pypy`).

Beyond those aforementioned items, this pull request is wonderful. I look
forward to merging it.

**Comment by medecau** [comment]
Hey @gruns 

1 - Yes. Tox installs the package and its dependencies in each environment before running the tests. By doing this tox is also testing that the dependencies are correct and the install process actually works. With tox the developer can fix problems where a dependency is missing from setup.py but is available in the dev environment. And it can also help surface when certain versions of python require different versions of a dependency.

2 - I was not aware of any problems with the naming. I have been using pypy3 for awhile. Thanks for the links.

3 - Done.

Thanks for the review.

**Comment by gruns** [comment]
Well, if Travis is any evidence, `pypy3` does the right thing and in turn runs Python 3 under PyPy.

```
$ python --version
Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:29:55)
[PyPy 2.4.0 with GCC 4.6.3]
```

From https://travis-ci.org/gruns/furl/jobs/223039792.

**Comment by gruns** [comment]
Merged.

Thank you, again, Pedro. Don't hesitate to let me know if there's anything I can do for you.

**Pull request merged**
