### PR TITLE
[Improvement] Fix code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/furl/issues/?category=recommended). This PR fixes a few of them.

### Summary of changes

- fixed ambiguous variable names
- Used literal syntax instead of function calls to create data structure
- Refactored `if` expression
- Refactored unnecessary `else` / `elif` when `if` block has a `return` statement
- added .deepsource.toml config

### CODE REVIEW

**Comment by withshubh** [comment]
Hi @gruns :wave: 
Please review this PR! :sparkles:

**Comment by withshubh** [comment]
@gruns I hope you're doing good.

Please have a look at this PR! :sparkles:

**Comment by gruns** [comment]
thank you for the PR

do you guys submit these PRs just to get deepsource.toml files in as many repos as possible?

**Comment by withshubh** [comment]
> thank you for the PR
> 
> do you guys submit these PRs just to get deepsource.toml files in as many repos as possible?

Haha :smiley: Nope @gruns 

We're just helping out Open Source maintainers by helping them integrate and activate DeepSource on their repositories. DeepSource is a code review automation tool that detects code quality issues and helps developers automatically fix some of them. DeepSource can be used to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

Did you check out the issues that were caught in [this repo](https://deepsource.io/gh/withshubh/furl/issues/).

**Comment by gruns** [comment]
deepsource is proprietary, ie not open source, correct?

**Comment by withshubh** [comment]
Yes, It is proprietary. Parts of DeepSource are built using Open Source tech So to give back to the community, DeepSource is free for open source forever. :sparkling_heart:

**Comment by gruns** [comment]
we're not going to integrate proprietary tech into furl unless manifest is a boon worth it. it's not here

also i would encourage you to announce your affiliation with your employer, and its non-open source tech, up front in the future

**Pull request closed without merging**
